### Excersise 1

In [1]:
# Sample code to remove noisy words from a text
noise_list = ["is", "a", "this", "..."]
def _remove_noise (input_text): 
    words = input_text.split()
    noise_free_words = [word for word in words if word not in noise_list]
    noise_free_text = "".join(noise_free_words) 
    return noise_free_text
print(_remove_noise("this is a sample text"))

sampletext


In [2]:
# Sample code to remove a regex pattern
import re
def remove_regex(input_text, regex_pattern):
    result = re.sub(regex_pattern, '', input_text)
    #result=re.sub(r'[\s]+'," ",result)
    return result
regex_pattern = "#[\w]*"
print(remove_regex("remove this #hashtag from analytics vidhya",
regex_pattern))

remove this  from analytics vidhya


### Excersise 2

In [3]:
pip install nltk

Note: you may need to restart the kernel to use updated packages.


In [4]:
from nltk.stem import PorterStemmer
tokenized = ["So", "many", "squids", "are", "jumping"]
stemmer = PorterStemmer()
stemmed = [stemmer.stem(token) for token in tokenized]
print(stemmed)

['so', 'mani', 'squid', 'are', 'jump']


In [5]:
from nltk.stem.porter import PorterStemmer
from nltk.tokenize import word_tokenize
stemmer = PorterStemmer()
# stem words in the list of tokenised words
def stem_words(text):
    word_tokens = word_tokenize(text)
    stems = [stemmer.stem(word) for word in word_tokens]
    return stems
text = "data science uses scientific methods algorithms and many types of processes"
stem_words(text)

['data',
 'scienc',
 'use',
 'scientif',
 'method',
 'algorithm',
 'and',
 'mani',
 'type',
 'of',
 'process']

In [6]:
import nltk
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

# Ensure you have the necessary NLTK resources
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
nltk.download('punkt')

def get_wordnet_pos(word): 
    """Map POS tag to first character lemmatize() accepts""" 
    tag = nltk.pos_tag([word])[0][1][0].upper() 
    tag_dict = {"J": wordnet.ADJ, 
                "N": wordnet.NOUN, 
                "V": wordnet.VERB, 
                "R": wordnet.ADV} 
 
    return tag_dict.get(tag, wordnet.NOUN) 
 
lemmatizer = WordNetLemmatizer() 
word = 'feet' 
print(lemmatizer.lemmatize(word, get_wordnet_pos(word))) 
 
sentence = "The striped bats are hanging on their feet for best" 
print([get_wordnet_pos(w) for w in nltk.word_tokenize(sentence)]) 
 
print([lemmatizer.lemmatize(w, get_wordnet_pos(w)) for w in 
nltk.word_tokenize(sentence)]) 

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\akanksh_02\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\akanksh_02\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\akanksh_02\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


foot
['n', 'v', 'n', 'v', 'v', 'n', 'n', 'n', 'n', 'a']
['The', 'strip', 'bat', 'be', 'hang', 'on', 'their', 'foot', 'for', 'best']


### Excersise 3

In [7]:
lookup_dict = {'rt':'Retweet', 'dm':'direct message', "awsm" : "awesome", "luv" :"love"} 
def _lookup_words(input_text): 
    words = input_text.split()  
    new_words = []  
    for word in words: 
        if word.lower() in lookup_dict: 
            word = lookup_dict[word.lower()] 
        new_words.append(word) 
    new_text = " ".join(new_words)  
    return new_text 
_lookup_words("RT this is a retweeted tweet by students")

'Retweet this is a retweeted tweet by students'

### Excersise 4

In [8]:
from nltk import word_tokenize, pos_tag 
text = "I am learning Natural Language Processing on Analytics Vidhya" 
tokens = word_tokenize(text) 
print(pos_tag(tokens))

[('I', 'PRP'), ('am', 'VBP'), ('learning', 'VBG'), ('Natural', 'NNP'), ('Language', 'NNP'), ('Processing', 'NNP'), ('on', 'IN'), ('Analytics', 'NNP'), ('Vidhya', 'NNP')]


In [9]:
from nltk.corpus import wordnet 
 
def get_wordnet_pos(word): 
    """Map POS tag to first character lemmatize() accepts""" 
    tag = nltk.pos_tag([word])[0][1][0].upper() 
    tag_dict = {"J": wordnet.ADJ, 
                "N": wordnet.NOUN, 
                "V": wordnet.VERB, 
                "R": wordnet.ADV} 
 
    return tag_dict.get(tag, wordnet.NOUN) 
sentence = "The striped bats are hanging on their feet for best" 
print([get_wordnet_pos(w) for w in nltk.word_tokenize(sentence)])

['n', 'v', 'n', 'v', 'v', 'n', 'n', 'n', 'n', 'a']


### Excersise 5

### Step1- Import Libraries

In [10]:
# for text preprocessing
import re
#import spacy
from nltk.corpus import stopwords
from nltk.stem.wordnet import WordNetLemmatizer
import string
# import vectorizers
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
# import numpy for matrix operation
import numpy as np
# import LDA from sklearn
from sklearn.decomposition import LatentDirichletAllocation
# to suppress warnings
from warnings import filterwarnings
filterwarnings('ignore')

D1 = 'I want to watch a movie this weekend.'
D2 = 'I went shopping yesterday. New Zealand won the World Test Championship by beating India by eight wickets at Southampton.'
D3 = 'I don’t watch cricket. Netflix and Amazon Prime have very good movies to watch.'
D4 = 'Movies are a nice way to chill however, this time I would like to paint and read some good books. Its been long!'
D5 = 'This blueberry milkshake is so good! Try reading Dr. Joe Dispenzas books. His work is such a game-changer! His books helped to learn so much about how our thoughts impact our biology and how we can all rewire our brains.'

# combining all the documents into a list:
corpus = [D1, D2, D3, D4, D5]
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\akanksh_02\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\akanksh_02\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\akanksh_02\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

### Step2 Text Preprocessing 

In [11]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import string

stop = set(stopwords.words('english'))
exclude = set(string.punctuation)
lemma = WordNetLemmatizer()

def clean(doc):
    stop_free = " ".join([i for i in doc.lower().split() if i not in stop])
    print(stop_free)  # This is inside the function

    punc_free = ''.join(ch for ch in stop_free if ch not in exclude)
    print(punc_free)  # This is inside the function

    normalized = " ".join(lemma.lemmatize(word) for word in punc_free.split())
    return normalized

clean_corpus = [clean(doc).split() for doc in corpus]

want watch movie weekend.
want watch movie weekend
went shopping yesterday. new zealand world test championship beating india eight wickets southampton.
went shopping yesterday new zealand world test championship beating india eight wickets southampton
don’t watch cricket. netflix amazon prime good movies watch.
don’t watch cricket netflix amazon prime good movies watch
movies nice way chill however, time would like paint read good books. long!
movies nice way chill however time would like paint read good books long
blueberry milkshake good! try reading dr. joe dispenzas books. work game-changer! books helped learn much thoughts impact biology rewire brains.
blueberry milkshake good try reading dr joe dispenzas books work gamechanger books helped learn much thoughts impact biology rewire brains


###  step3 Convert Text into Numerical Representation


In [12]:
tf_idf_vectorizer = TfidfVectorizer( tokenizer=lambda doc:doc,lowercase=False)
#tf_idf_vectorizer = TfidfVectorizer( lowercase=False)
# Converting text into numerical representation
#cv_vectorizer = CountVectorizer(tokenizer=lambda doc: doc,lowercase=False)
# Array from TF-IDF Vectorizer
tf_idf_arr = tf_idf_vectorizer.fit_transform(clean_corpus)
# Array from Count Vectorizer
#cv_arr = cv_vectorizer.fit_transform(clean_corpus)
import pandas as pd
df=pd.DataFrame(tf_idf_arr.toarray(),columns=tf_idf_vectorizer.get_feature_names_out())
print(df)

     amazon  beating   biology  blueberry      book     brain  championship  \
0  0.000000  0.00000  0.000000   0.000000  0.000000  0.000000       0.00000   
1  0.000000  0.27735  0.000000   0.000000  0.000000  0.000000       0.27735   
2  0.342983  0.00000  0.000000   0.000000  0.000000  0.000000       0.00000   
3  0.000000  0.00000  0.000000   0.000000  0.237416  0.000000       0.00000   
4  0.000000  0.00000  0.223316   0.223316  0.360339  0.223316       0.00000   

      chill   cricket  dispenzas  ...     watch       way   weekend     went  \
0  0.000000  0.000000   0.000000  ...  0.458270  0.000000  0.568014  0.00000   
1  0.000000  0.000000   0.000000  ...  0.000000  0.000000  0.000000  0.27735   
2  0.000000  0.342983   0.000000  ...  0.553433  0.000000  0.000000  0.00000   
3  0.294271  0.000000   0.000000  ...  0.000000  0.294271  0.000000  0.00000   
4  0.000000  0.000000   0.223316  ...  0.000000  0.000000  0.000000  0.00000   

    wicket      work    world     would  yes

In [13]:
# Creating vocabulary array which will represent all the corpus
vocab_tf_idf = tf_idf_vectorizer.get_feature_names_out()
# get the vocb list
vocab_tf_idf
# Implementation of LDA:
lda_model = LatentDirichletAllocation(n_components = 6, max_iter =20, random_state = 20)
X_topics = lda_model.fit_transform(tf_idf_arr)
print(X_topics)
# .components_ gives us our topic distribution
topic_words = lda_model.components_
#print(topic_words)

[[0.71953211 0.05629854 0.05603104 0.05607016 0.05603407 0.05603407]
 [0.03620009 0.03619922 0.81899585 0.03619839 0.03620323 0.03620323]
 [0.0449248  0.7761292  0.04472847 0.0447796  0.04471896 0.04471896]
 [0.03652797 0.03650944 0.03649304 0.81757645 0.03644655 0.03644655]
 [0.03142363 0.03146103 0.84279078 0.03147025 0.03142716 0.03142716]]


### step 4a Retrive the topics

In [14]:
### or for i, topic in enumerate(clean_corpus, start=1): print(f"Topic {i} {topic}") ###

In [15]:
# Define the number of words that we want to print in every topic
n_top_words = 5

for i, topic_dist in enumerate(topic_words):
    # np.argsort sorts an array or a list or the matrix according to their values
    sorted_topic_dist = np.argsort(topic_dist)
    
    # Next, to view the actual words present in those indexes, we can make use of the vocab created earlier
    print(np.array(vocab_tf_idf))
    print(np.array(vocab_tf_idf)[sorted_topic_dist])
    print("\n ------------------------------")
    
    # Extract the words from the vocabulary using the sorted_topic_indexes
    # Obtain topics + words
    # This topic_words variable contains the topics as well as the respective words present in those topics
    topic_words = np.array(vocab_tf_idf)[sorted_topic_dist]
    topic_words = topic_words[:-(n_top_words + 1):-1]
    print(f"Topic {i + 1}", topic_words)
    print("\n ------------------------------")

['amazon' 'beating' 'biology' 'blueberry' 'book' 'brain' 'championship'
 'chill' 'cricket' 'dispenzas' 'don’t' 'dr' 'eight' 'gamechanger' 'good'
 'helped' 'however' 'impact' 'india' 'joe' 'learn' 'like' 'long'
 'milkshake' 'movie' 'much' 'netflix' 'new' 'nice' 'paint' 'prime' 'read'
 'reading' 'rewire' 'shopping' 'southampton' 'test' 'thought' 'time' 'try'
 'want' 'watch' 'way' 'weekend' 'went' 'wicket' 'work' 'world' 'would'
 'yesterday' 'zealand']
['like' 'would' 'way' 'however' 'time' 'nice' 'chill' 'paint' 'long'
 'read' 'netflix' 'prime' 'amazon' 'cricket' 'don’t' 'rewire' 'thought'
 'try' 'work' 'milkshake' 'reading' 'much' 'joe' 'biology' 'impact'
 'helped' 'gamechanger' 'blueberry' 'dr' 'dispenzas' 'brain' 'learn'
 'beating' 'world' 'wicket' 'went' 'championship' 'test' 'shopping'
 'eight' 'new' 'yesterday' 'india' 'southampton' 'zealand' 'book' 'good'
 'movie' 'watch' 'want' 'weekend']

 ------------------------------
Topic 1 ['weekend' 'want' 'watch' 'movie' 'good']

 -------

### Step 4b Annotating the topics the documents

In [16]:
# Assuming you have already defined lda_model and tf_idf_arr

# To view the topics assigned to the documents:
doc_topic = lda_model.transform(tf_idf_arr)
print(doc_topic)

# Iterating over every value until the end value
for n in range(doc_topic.shape[0]):
    # argmax() gives the maximum index value
    topic_doc = doc_topic[n].argmax()
    # Document is n+1
    print("Document", n+1, "-- Topic:", topic_doc)

[[0.71953211 0.05629854 0.05603104 0.05607016 0.05603407 0.05603407]
 [0.03620009 0.03619922 0.81899585 0.03619839 0.03620323 0.03620323]
 [0.0449248  0.7761292  0.04472847 0.0447796  0.04471896 0.04471896]
 [0.03652797 0.03650944 0.03649304 0.81757645 0.03644655 0.03644655]
 [0.03142363 0.03146103 0.84279078 0.03147025 0.03142716 0.03142716]]
Document 1 -- Topic: 0
Document 2 -- Topic: 2
Document 3 -- Topic: 1
Document 4 -- Topic: 3
Document 5 -- Topic: 2
